### ISSUE TITLE
[Improve]Make the HttpService class public and add more public customizable constructors

### ISSUE THREAD

**Issue by hacfox** [crisogray/NeoSwift#3]
@crisogray Hello, I have already written down some questions there. Could you please evaluate them and consider whether it is possible to address these two important points within the existing dependency library? Of course, I have other questions that I haven't listed yet, and I will continue to add them later. [source link](https://github.com/AxLabs/grantshares/issues/78#issuecomment-1558637762)

**Comment by hacfox** [comment]
`ScriptBuilder` also has this issue. After developers import the package, they are unable to use the SDK properly. So I may think it's not just an issue with these two classes, there may be the same problem with other code as well. Could you please check the code? 😄

**Comment by crisogray** [comment]
Thanks for highlighting this, an oversight from me. Have been through and added public modification to the obvious ones. Will be looking for more of the non-obvious ones

**Comment by crisogray** [comment]
Have been through more thoroughly and added public scoping where it was missing, happy for now
