### ISSUE TITLE
[Suggestion]Lowering the minimum required version of the mobile operating system for mobile devices

### ISSUE THREAD

**Issue by hacfox** [crisogray/NeoSwift#5]
Based on Xcode and Apple's recommendations, the minimum supported iOS version is currently iOS 12. You cannot assume that all users will always have the latest version of the operating system.

**Comment by crisogray** [comment]
One of the things blocking this was easy enough to fix. The minimum iOS version is now 13 (from 14), and macOS 10.15. These are in line with the minimums of some of the dependencies used (elliptic curve library and Combine from Apple used for Rx).

I think these are acceptable, especially given the recent WWDC updates which advance each operating system by a version, quite possibly the minimum recommendation too.
