### ISSUE TITLE
[Improve]Fatal Error in buildContractCallAndUnwrapIterator Function of ScriptBuilder: Negative Value Representation Issue

### ISSUE THREAD

**Issue by hacfox** [crisogray/NeoSwift#6]
The `buildContractCallAndUnwrapIterator` function in `ScriptBuilder` is encountering a fatal error with the message: "Fatal error: Negative value is not representable." This error suggests that the function is unable to handle negative values appropriately, leading to a crash. The negative value representation issue needs to be addressed and resolved to ensure the smooth functioning of the `buildContractCallAndUnwrapIterator` function.

**Comment by crisogray** [comment]
Have added proper error propagation here and in a couple of other places where I had just been printing due to prior indecision. Will investigate further before closing. Are you able to share the code that resulted in this error? Thanks

**Comment by crisogray** [comment]
Have also managed to repricate fully and have had added safety to the error causing lines, will be in next commit
