### ISSUE TITLE
[Improve]Unclear Error Type

### ISSUE THREAD

**Issue by hacfox** [crisogray/NeoSwift#8]
Currently, only strings are being returned, and as developers, it's difficult to determine the specific error. The best practice would be to have a class that centrally manages these error types, allowing developers to make error judgments based on this class.

before:
<img width="1041" alt="image" src="https://github.com/crisogray/NeoSwift/assets/24224633/4e595ceb-c927-4980-9e9b-f56c601816f4">

after:
```swift
enum N3Error {
	case InvalidPrivateKey

	case InvalidPassword

	case InvalidAddress

	case InvalidNonce

	case ...
	...
}

// other codes
...
```

**Comment by crisogray** [comment]
Agree on this, have been putting off... WIP

**Comment by crisogray** [comment]
Have added error typing throughout
